interface Plant {

    // DB assigned ID. Should only be generated by DB, therfore is readonly.
    readonly _id?: string;

    // Plant name
    name: string;

    // maximum depth in mm to plant the seeds
    maxPlantingDepth?: number;

    // minimum depth in mm to plant the seeds
    minPlantingDepth?: number;

    // traget planting depth. Will average max and min if not directly provided.
    plantingDepth: number;

    // self-explanatory
    daysToGerminate: number;

    // Maxiumum height in mm the plant is expected to grow.
    avgMaxHeight: number;

    // Maxiumum diameter in mm the plant is expected to grow.
    avgMaxDiameter: number;

}