interface PlantInterface {

    // DB assigned ID. Should only be generated by DB, therfore is readonly.
    readonly id?: string;

    // Plant name
    name: string;

    // maximum depth in mm to plant the seeds
    height?: number;

    // minimum depth in mm to plant the seeds
    width?: number;

    // traget planting depth. Will average max and min if not directly provided.
    depth: number;

    // self-explanatory
    daysToGerminate: number;

    // Maxiumum height in mm the plant is expected to grow.
    description: number;

}

export default PlantInterface;